window.SITE_DATA = {
  company: {
    name: "Erkhet Solar Tours LLC",
    nameMn: "Эрхэт Солар Турс ХХК",
    founded: "2016",
    phone: "+97695633513",
    phoneLabel: "+976 95633513",
    email: "info@erkhtsolartours.mn",
    logo: "logo.jpg",
    address: ""
  },
  links: {
    facebook: "https://www.facebook.com/share/1bzQfpFhu3/",
    telegram: "",
    wechat: "",
    telegramQr: "telegram-qr.jpg",
    wechatQr: "wechat-qr.jpg"
  },
  payment: {
    methods: ["QPay (MN)", "Visa/Mastercard (Stripe)"],
    instructions: "",
    qpayLink: "",
    stripePaymentLink: ""
  },
  nav: [
    { key: "nav.home", href: "index.html", page: "home" },
    { key: "nav.about", href: "about.html", page: "about" },
    { key: "nav.services", href: "services.html", page: "services" },
    { key: "nav.tours", href: "tours.html", page: "tours" },
    { key: "nav.destinations", href: "destinations.html", page: "destinations" },
    { key: "nav.contact", href: "contact.html", page: "contact" }
  ],
  services: [
    {
      icon: "🧭",
      title: { mn: "Төлөвлөсөн аяллууд", en: "Scheduled tours", zh: "固定行程", ru: "Плановые туры" },
      desc: { mn: "Тогтмол маршрут, баталгаатай зохион байгуулалт.", en: "Fixed routes with reliable operations." }
    },
    {
      icon: "✨",
      title: { mn: "Зөвхөн танд зориулсан аялал", en: "Private custom tours", zh: "定制私享游", ru: "Индивидуальные туры" },
      desc: { mn: "Таны сонирхол, төсөвт тохируулсан хөтөлбөр.", en: "Itineraries tailored to your needs and budget." }
    },
    {
      icon: "🎯",
      title: { mn: "Зорилтот аялал", en: "Special-interest tours", zh: "主题旅行", ru: "Тематические туры" },
      desc: { mn: "Түүх, соёл, байгальд чиглэсэн тусгай аялал.", en: "Focused tours for culture, history, and nature." }
    },
    {
      icon: "💼",
      title: { mn: "Бизнес аялал", en: "Business travel", zh: "商务出行", ru: "Деловые поездки" },
      desc: { mn: "Ажлын уулзалт, логистик, аяллыг нэг цэгээс.", en: "Business logistics and travel from one team." }
    },
    {
      icon: "🗺️",
      title: { mn: "Захиалгат аялал төлөвлөлт", en: "Custom trip planning", zh: "定制行程规划", ru: "Планирование под заказ" },
      desc: { mn: "Бүрэн зөвлөх үйлчилгээ, үе шаттай төлөвлөлт.", en: "Full consulting and step-by-step planning." }
    }
  ],
  values: [
    { mn: "Аюулгүй байдал нэн тэргүүнд", en: "Safety first", zh: "安全第一", ru: "Безопасность прежде всего" },
    { mn: "Хариуцлагатай аялал жуулчлал", en: "Responsible tourism", zh: "责任旅游", ru: "Ответственный туризм" },
    { mn: "Соёлын хүндэтгэл", en: "Respect for culture", zh: "尊重文化", ru: "Уважение к культуре" },
    { mn: "Харилцагчийн сэтгэл ханамж", en: "Customer satisfaction", zh: "客户满意", ru: "Удовлетворенность клиентов" },
    { mn: "Шударга хамтын ажиллагаа", en: "Fair cooperation", zh: "公平合作", ru: "Честное партнерство" }
  ],
  mission: {
    mn: "Монгол орны байгаль, түүх, соёлыг мэргэжлийн түвшинд танилцуулсан аюулгүй, сэтгэл ханамж өндөр аяллын үйлчилгээг хүргэх.",
    en: "Deliver safe, high-satisfaction travel services that professionally introduce Mongolia’s nature, history, and culture."
  },
  businessDirections: [
    { mn: "Гадаадын жуулчдыг Монгол орноор аялуулах", en: "Inbound travel for international tourists" },
    { mn: "Монгол аялагчдын гадаад аяллыг зохион байгуулах", en: "Outbound travel for Mongolian tourists" },
    { mn: "Монгол дотоодын аяллыг зохион байгуулах", en: "Domestic travel within Mongolia" }
  ],
  featuredTourIds: ["ub-4d", "gobi-5d", "khangai-7d", "aglag-1d", "gobi-2d"],
  tours: [
    {
      id: "ub-4d",
      category: "multi",
      title: { mn: "УБ хот орчмын аялал", en: "Ulaanbaatar Area Tour" },
      duration: { mn: "4 өдөр / 4 шөнө", en: "4 days / 4 nights" },
      price: "2,300,000 ₮",
      route: { mn: "Замын-Үүд - Сайншанд - УБ - Морьт хөшөөт цогцолбор", en: "Zamiin-Uud - Sainshand - UB - Chinggis Statue" },
      image: "https://images.unsplash.com/photo-1472396961693-142e6e269027?q=80&w=1400&auto=format&fit=crop",
      overview: { mn: "Хот, түүх, ахуйг тэнцвэржүүлсэн 4 өдрийн маршрут." },
      itinerary: [
        "1 өдөр: Замын-Үүдээс Сайншанд, Хамрын хийд",
        "2 өдөр: УБ хотын аялал – Талбай, Чингис хаан музей, Гандан, чөлөөт цаг",
        "3 өдөр: Монгол ахуйтай танилцах аялал",
        "4 өдөр: Чингис хааны морьт хөшөөт цогцолбор, вагонд сууж буцах"
      ]
    },
    {
      id: "gobi-5d",
      category: "multi",
      title: { mn: "Говийн аялал", en: "Gobi Tour" },
      duration: { mn: "5 өдөр / 5 шөнө", en: "5 days / 5 nights" },
      price: "2,500,000 ₮",
      route: { mn: "Сайншанд - УБ - Мандалговь - Цагаан суварга - Ёлын ам", en: "Sainshand - UB - Mandalgovi - Tsagaan Suvarga - Yol Valley" },
      image: "https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?q=80&w=1400&auto=format&fit=crop",
      overview: { mn: "Говийн гол цэгүүдийг хамарсан бүтэн хөтөлбөр." },
      itinerary: [
        "1 өдөр: Замын-Үүдээс Сайншанд, Хамрын хийд, УБ-д ирнэ",
        "2 өдөр: УБ хотын аялал",
        "3 өдөр: Мандалговь, Цагаан суварга, Даланзадгад",
        "4 өдөр: Мухар шивэртийн ам, Ёлын ам, УБ руу буцна",
        "5 өдөр: Чингис хааны морьт хөшөөт цогцолбор, буцна"
      ]
    },
    {
      id: "khangai-7d",
      category: "multi",
      title: { mn: "Хангайн аялал", en: "Khangai Tour" },
      duration: { mn: "7 өдөр", en: "7 days" },
      price: "3,300,000 ₮",
      route: { mn: "Сайншанд - УБ - Хөвсгөл - Дархад", en: "Sainshand - UB - Khuvsgul - Darkhad" },
      image: "https://images.unsplash.com/photo-1501785888041-af3ef285b470?q=80&w=1400&auto=format&fit=crop",
      overview: { mn: "Хангай, Хөвсгөлийн байгаль, соёлын урт маршрут." },
      itinerary: [
        "1 өдөр: Замын-Үүдээс Сайншанд, Хамрын хийд",
        "2 өдөр: УБ хотын аялал",
        "3 өдөр: Хөвсгөл аймаг, Мөрөн сум",
        "4 өдөр: Рэнчинлхүмбэ, Жаргант гол, Дархадын 13 овоо",
        "5 өдөр: Хөвсгөл нуур",
        "6 өдөр: УБ буцна",
        "7 өдөр: Чингис хааны морьт хөшөөт цогцолбор, буцна"
      ]
    },
    {
      id: "gobi-2d",
      category: "short",
      title: { mn: "Говийн богино аялал", en: "Short Gobi Tour" },
      duration: { mn: "2 өдөр / 1 шөнө", en: "2 days / 1 night" },
      price: "",
      route: { mn: "Цагаан суварга, Ёлын ам, Мухар шивэртийн ам", en: "Tsagaan Suvarga, Yol Valley, Mukhar Shiver" },
      image: "https://images.unsplash.com/photo-1472396961693-142e6e269027?q=80&w=1400&auto=format&fit=crop",
      overview: { mn: "Дотоодын богино хугацааны Говийн аялал." },
      itinerary: ["1-2 өдөр: Цагаан суварга, Ёлын ам, Мухар шивэртийн ам"]
    },
    {
      id: "eejkhairkhan-1d",
      category: "short",
      title: { mn: "Ээж хайрхан, Манзушир хийдийн туурь", en: "Eej Khairkhan & Manzushir Ruins" },
      duration: { mn: "1 өдөр", en: "1 day" },
      price: "",
      route: { mn: "Төв аймаг", en: "Tuv Province" },
      image: "https://images.unsplash.com/photo-1521292270410-a8c4d716d518?q=80&w=1400&auto=format&fit=crop",
      overview: { mn: "Соёл, байгалийг хослуулсан 1 өдрийн аялал." },
      itinerary: ["1 өдөр: Ээж хайрхан, Манзушир хийдийн туурь"]
    },
    {
      id: "aglag-1d",
      category: "short",
      title: { mn: "Аглаг бүтээлийн хийд", en: "Aglag Monastery" },
      duration: { mn: "1 өдөр", en: "1 day" },
      price: "",
      route: { mn: "УБ орчим", en: "Near Ulaanbaatar" },
      image: "https://images.unsplash.com/photo-1518509562904-e7ef99cdcc86?q=80&w=1400&auto=format&fit=crop",
      overview: { mn: "Өдрийн мөргөл, байгалийн тайван орчин." },
      itinerary: ["1 өдөр: Аглаг бүтээлийн хийд"]
    },
    {
      id: "saihanhotol-1d",
      category: "short",
      title: { mn: "Сайхны хөтөл, Ээж мод", en: "Saihan Khotol & Mother Tree" },
      duration: { mn: "1 өдөр", en: "1 day" },
      price: "",
      route: { mn: "Төв бүс", en: "Central region" },
      image: "https://images.unsplash.com/photo-1441974231531-c6227db76b6e?q=80&w=1400&auto=format&fit=crop",
      overview: { mn: "Амралтын өдрийн гэр бүлд ээлтэй маршрут." },
      itinerary: ["1 өдөр: Сайхны хөтөл, Ээж мод"]
    }
  ],
  destinations: [
    { key: "central", title: { mn: "Төв бүс", en: "Central Region" }, items: ["Элсэн тасархай", "Эрдэнэзуу хийд", "Төвхөн хийд"] },
    { key: "khangai", title: { mn: "Хангайн бүс", en: "Khangai Region" }, items: ["Чулуутын хавцал", "Тэрхийн цагаан нуур", "Хоргын тогоо", "Улаан цутгалан", "Хүйсийн найман нуур", "Хөвсгөл нуур", "Жаргант гол", "Тайхар чулуу", "Цамбагарав", "Отгонтэнгэр", "Өгий нуур", "Хяргас нуур", "Уран тогоо уул", "Даян дээрхийн агуй", "Дархадын арван гурван овоо", "Цаатны нутаг", "Алтай Таван богд"] },
    { key: "east", title: { mn: "Зүүн бүс", en: "Eastern Region" }, items: ["Хар зүрхний Хөх нуур", "Аварга тосон рашаан", "Хэрхлүүр Сарьдаг", "Алтан овоо", "Шилийн Богд", "Ганга нуур", "Оргихын булаг", "Торой бандийн хөшөө", "Дэлүүн болдог", "Буйр нуур", "Онон мөрний Зүрхэн арал"] },
    { key: "gobi", title: { mn: "Говийн бүс", en: "Gobi Region" }, items: ["Их бага газрын чулуу", "Цагаан суварга", "Хонгорын элс", "Баянзаг", "Ёлын ам", "Хэрмэн цав", "Хамрын хийд", "Дэмчогийн хийд"] },
    { key: "ub", title: { mn: "Улаанбаатар орчим", en: "Around Ulaanbaatar" }, items: ["Сүхбаатарын талбай", "Гандан", "Зайсан", "УИД", "Чингис хааны морьт хөшөөт цогцолбор"] }
  ],
  i18n: {
    mn: {
      "brand.short": "Эрхэт Солар Турс",
      "brand.full": "Эрхэт Солар Турс ХХК",
      "nav.home": "Нүүр",
      "nav.about": "Бидний тухай",
      "nav.services": "Үйлчилгээ",
      "nav.tours": "Аяллууд",
      "nav.destinations": "Чиглэлүүд",
      "nav.contact": "Холбоо барих",
      "common.more": "Дэлгэрэнгүй",
      "common.viewAll": "Бүгдийг үзэх",
      "common.details": "Дэлгэрэнгүй",
      "common.sendInquiry": "Лавлагаа илгээх",
      "common.duration": "Хугацаа",
      "common.price": "Үнэ",
      "common.route": "Чиглэл",
      "home.heroEyebrow": "2016 оноос хойш",
      "home.heroTitle": "Монгол орноор аюулгүй, тав тухтай, дурсамжтай аялаарай",
      "home.heroSubtitle": "Эрхэт Солар Турс ХХК нь Монгол орны байгаль, түүх, соёлыг мэргэжлийн түвшинд танилцуулсан аюулгүй, сэтгэл ханамж өндөр аяллын үйлчилгээг санал болгож байна.",
      "home.ctaTours": "Аяллууд үзэх",
      "home.ctaPlan": "Аяллаа төлөвлөх",
      "home.aboutTitle": "Бидний тухай",
      "home.aboutSnippet": "Эрхэт Солар Турс ХХК нь 2016 оноос эхлэн дотоод, гадаад, inbound/outbound чиглэлээр мэргэжлийн аяллын үйлчилгээ үзүүлж байна.",
      "home.servicesTitle": "Үйлчилгээ",
      "home.featuredToursTitle": "Онцлох аяллууд",
      "home.regionsTitle": "Аяллын бүсүүд",
      "home.valuesTitle": "Яагаад биднийг сонгох вэ",
      "home.contactCtaTitle": "Аяллын зөвлөгөө хэрэгтэй юу?",
      "home.contactCtaText": "Хэдэн хүн, хэдэн өдөр, сонирхож буй маршрутаа илгээгээрэй.",
      "about.title": "Бидний тухай",
      "about.subtitle": "Итгэл даах, аюулгүй, хариуцлагатай аяллын түнш.",
      "about.founded": "Үүсгэн байгуулагдсан он",
      "about.directions": "Үйл ажиллагааны чиглэл",
      "about.mission": "Зорилго",
      "about.values": "Үнэт зүйлс",
      "about.advantages": "Бидний давуу тал",
      "about.adv1": "Олон жилийн туршлагатай баг",
      "about.adv2": "Орон нутгийн бодит мэдлэгтэй маршрутууд",
      "about.adv3": "Тодорхой, ойлгомжтой харилцаа",
      "services.title": "Үйлчилгээ",
      "services.subtitle": "Таны зорилгод тохирсон аяллын шийдлүүд.",
      "tours.title": "Аяллууд",
      "tours.subtitle": "Олон өдрийн болон дотоодын богино аяллуудаа сонгоорой.",
      "tours.filterAll": "Бүгд",
      "tours.filterMulti": "Олон өдрийн аяллууд",
      "tours.filterShort": "Дотоодын богино аяллууд",
      "tours.search": "Аялал хайх",
      "tours.none": "Тохирох аялал олдсонгүй.",
      "detail.included": "Үүнд багтсан",
      "detail.notIncluded": "Үүнд багтаагүй",
      "detail.inquiry": "Энэ аяллаар лавлагаа илгээх",
      "dest.title": "Чиглэлүүд",
      "dest.subtitle": "Монгол орны аяллын бүсүүдээр ангилсан чиглэлүүд.",
      "contact.title": "Холбоо барих / Лавлагаа",
      "contact.subtitle": "Албан ёсны мэдээллээр шууд холбогдож, хүсэлтээ илгээнэ үү.",
      "contact.formTitle": "Лавлагааны форм",
      "contact.name": "Нэр",
      "contact.phone": "Утасны дугаар",
      "contact.email": "И-мэйл",
      "contact.tour": "Сонирхож буй аялал",
      "contact.people": "Хэдэн хүн явах вэ",
      "contact.days": "Хэдэн өдөр явах вэ",
      "contact.note": "Нэмэлт тайлбар",
      "contact.submit": "Илгээх",
      "contact.official": "Албан ёсны холбоо барих мэдээлэл",
      "contact.payment": "Төлбөрийн мэдээлэл",
      "contact.methods": "Төлбөрийн аргууд",
      "contact.instructions": "Төлбөрийн заавар",
      "contact.qr": "QR холбоос",
      "footer.rights": "Бүх эрх хуулиар хамгаалагдсан."
    },
    en: {
      "brand.short": "Erkhet Solar Tours",
      "brand.full": "Erkhet Solar Tours LLC",
      "nav.home": "Home",
      "nav.about": "About",
      "nav.services": "Services",
      "nav.tours": "Tours",
      "nav.destinations": "Destinations",
      "nav.contact": "Contact",
      "common.more": "Learn more",
      "common.viewAll": "View all",
      "common.details": "Details",
      "common.sendInquiry": "Send enquiry",
      "common.duration": "Duration",
      "common.price": "Price",
      "common.route": "Route",
      "home.heroEyebrow": "Since 2016",
      "home.heroTitle": "Travel Mongolia safely, comfortably, and memorably",
      "home.heroSubtitle": "Erkhet Solar Tours LLC provides safe, high-satisfaction trips introducing Mongolia’s nature, history, and culture.",
      "home.ctaTours": "Explore tours",
      "home.ctaPlan": "Plan my trip",
      "home.aboutTitle": "About Us",
      "home.aboutSnippet": "Since 2016, we have organized inbound, outbound, and domestic tours with a professional team.",
      "home.servicesTitle": "Services",
      "home.featuredToursTitle": "Featured Tours",
      "home.regionsTitle": "Destination Regions",
      "home.valuesTitle": "Why Choose Us",
      "home.contactCtaTitle": "Need travel advice?",
      "home.contactCtaText": "Send your group size, trip days, and preferred route.",
      "about.title": "About Us",
      "about.subtitle": "A reliable partner for safe and responsible travel.",
      "about.founded": "Founded",
      "about.directions": "Business Directions",
      "about.mission": "Mission",
      "about.values": "Core Values",
      "about.advantages": "Our Strengths",
      "about.adv1": "Experienced team",
      "about.adv2": "Practical routes with local expertise",
      "about.adv3": "Clear communication",
      "services.title": "Services",
      "services.subtitle": "Travel solutions tailored to your goals.",
      "tours.title": "Tours",
      "tours.subtitle": "Choose from multi-day and short domestic tours.",
      "tours.filterAll": "All",
      "tours.filterMulti": "Multi-day Tours",
      "tours.filterShort": "Short Domestic Tours",
      "tours.search": "Search tours",
      "tours.none": "No matching tours found.",
      "detail.included": "Included",
      "detail.notIncluded": "Not included",
      "detail.inquiry": "Enquire this tour",
      "dest.title": "Destinations",
      "dest.subtitle": "Destinations organized by Mongolia’s major regions.",
      "contact.title": "Contact / Enquiry",
      "contact.subtitle": "Reach us via official contacts and send your enquiry.",
      "contact.formTitle": "Enquiry form",
      "contact.name": "Name",
      "contact.phone": "Phone",
      "contact.email": "Email",
      "contact.tour": "Interested tour",
      "contact.people": "Number of travelers",
      "contact.days": "Travel days",
      "contact.note": "Additional note",
      "contact.submit": "Send",
      "contact.official": "Official contact information",
      "contact.payment": "Payment information",
      "contact.methods": "Payment methods",
      "contact.instructions": "Payment instructions",
      "contact.qr": "QR contact",
      "footer.rights": "All rights reserved."
    },
    zh: {},
    ru: {}
  }
};
